### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Alejandro-Trave-To-dos#1]
# Revisión - Aprobado :white_check_mark:

## Feedback
- Bien hecho @Atravep ⭐⭐⭐

## Estilo de código y limpieza
- Buen uso del `useState` y del `useEffect`

## Mejores prácticas/comentarios
- Este componente `List`,  muestra un buen uso de los conceptos básicos de React y es un buen ejemplo de cómo crear una aplicación simple pero funcional utilizando hooks y componentes funcionales.
- Puedes cambiar el `<title>` de tu proyecto en el archivo `template.html` 
![Captura de pantalla de 2024-04-28 23-04-02](https://github.com/4GeeksAcademy/Alejandro-Trave-To-dos/assets/139759297/47f0493f-faeb-499f-baa6-9ce3de9bd499)
- Recuerda que los nombres de los componentes así como sus archivos .jsx, deberían ir en mayúsculas 
![Captura de pantalla de 2024-04-28 23-08-45](https://github.com/4GeeksAcademy/Alejandro-Trave-To-dos/assets/139759297/951c85e7-6dd1-4b24-8bb5-619fb707031d)

**Comment by Atravep** [comment]
Siempre se me olvida lo de los componentes en mayúscula!! Gracias.

**Comment by EduardoHernandezGuzman** [comment]
Estás haciendo muy buen trabajo Alejandro
